// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViSinhVien.Api.Data;

#nullable disable

namespace ViSinhVien.Api.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20261006160300_InitialFinance")]
    partial class InitialFinance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViSinhVien.Api.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Name")
                        .IsUnique();

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_category_name", "length(trim(name)) > 0");

                            t.HasCheckConstraint("ck_category_type", "type IN ('income', 'expense')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsArchived = false,
                            Name = "Ăn uống",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 2L,
                            IsArchived = false,
                            Name = "Đi lại",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 3L,
                            IsArchived = false,
                            Name = "Học tập",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 4L,
                            IsArchived = false,
                            Name = "Sinh hoạt",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 5L,
                            IsArchived = false,
                            Name = "Gia đình hỗ trợ",
                            Type = "income"
                        },
                        new
                        {
                            Id = 6L,
                            IsArchived = false,
                            Name = "Làm thêm",
                            Type = "income"
                        });
                });

            modelBuilder.Entity("ViSinhVien.Api.Models.FinanceTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AmountVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_vnd");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TransactionDate");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transaction_amount", "amount_vnd > 0 AND amount_vnd <= 1000000000000");
                        });
                });

            modelBuilder.Entity("ViSinhVien.Api.Models.MonthlyBudget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BudgetMonth")
                        .HasColumnType("date")
                        .HasColumnName("budget_month");

                    b.Property<long>("LimitVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("limit_vnd");

                    b.HasKey("Id");

                    b.HasIndex("BudgetMonth")
                        .IsUnique();

                    b.ToTable("monthly_budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_budget_limit", "limit_vnd > 0 AND limit_vnd <= 1000000000000");

                            t.HasCheckConstraint("ck_budget_month", "EXTRACT(DAY FROM budget_month) = 1");
                        });
                });

            modelBuilder.Entity("ViSinhVien.Api.Models.FinanceTransaction", b =>
                {
                    b.HasOne("ViSinhVien.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
