CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006160300_InitialFinance') THEN
    CREATE TABLE categories (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        type character varying(10) NOT NULL,
        is_archived boolean NOT NULL,
        CONSTRAINT "PK_categories" PRIMARY KEY (id),
        CONSTRAINT ck_category_name CHECK (length(trim(name)) > 0),
        CONSTRAINT ck_category_type CHECK (type IN ('income', 'expense'))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006160300_InitialFinance') THEN
    CREATE TABLE monthly_budgets (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        budget_month date NOT NULL,
        limit_vnd bigint NOT NULL,
        CONSTRAINT "PK_monthly_budgets" PRIMARY KEY (id),
        CONSTRAINT ck_budget_limit CHECK (limit_vnd > 0 AND limit_vnd <= 1000000000000),
        CONSTRAINT ck_budget_month CHECK (EXTRACT(DAY FROM budget_month) = 1)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006160300_InitialFinance') THEN
    CREATE TABLE transactions (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        category_id bigint NOT NULL,
        amount_vnd bigint NOT NULL,
        transaction_date date NOT NULL,
        note character varying(500) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_transactions" PRIMARY KEY (id),
        CONSTRAINT ck_transaction_amount CHECK (amount_vnd > 0 AND amount_vnd <= 1000000000000),
        CONSTRAINT "FK_transactions_categories_category_id" FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006160300_InitialFinance') THEN
    INSERT INTO categories (id, is_archived, name, type)
    VALUES (1, FALSE, 'Ăn uống', 'expense');
    INSERT INTO categories (id, is_archived, name, type)
    VALUES (2, FALSE, 'Đi lại', 'expense');
    INSERT INTO categories (id, is_archived, name, type)
    VALUES (3, FALSE, 'Học tập', 'expense');
    INSERT INTO categories (id, is_archived, name, type)
    VALUES (4, FALSE, 'Sinh hoạt', 'expense');
    INSERT INTO categories (id, is_archived, name, type)
    VALUES (5, FALSE, 'Gia đình hỗ trợ', 'income');
    INSERT INTO categories (id, is_archived, name, type)
    VALUES (6, FALSE, 'Làm thêm', 'income');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006160300_InitialFinance') THEN
    CREATE UNIQUE INDEX "IX_categories_type_name" ON categories (type, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006160300_InitialFinance') THEN
    CREATE UNIQUE INDEX "IX_monthly_budgets_budget_month" ON monthly_budgets (budget_month);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006160300_InitialFinance') THEN
    CREATE INDEX "IX_transactions_category_id" ON transactions (category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006160300_InitialFinance') THEN
    CREATE INDEX "IX_transactions_transaction_date" ON transactions (transaction_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006160300_InitialFinance') THEN
    PERFORM setval(
        pg_get_serial_sequence('categories', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM categories) + 1,
            nextval(pg_get_serial_sequence('categories', 'id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006160300_InitialFinance') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261006160300_InitialFinance', '8.0.11');
    END IF;
END $EF$;
COMMIT;

